server:
  port: 8080

# mysql Setting
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lh_db?serverTimezone=UTC&useUnicode=true&Encoding=utf8&useSSL=false
    username: root
    password: root